name: 'Publish on Docker Hub'
author: 'Hannes Hochreiner <hannes@hochreiner.net>'
description: 'Publish a package on Docker Hub'
inputs:
  docker-user-name:
    description: 'Docker user name'
    required: true
  docker-token:
    description: 'Docker token'
    required: true
  docker-targets:
    description: 'Docker targets'
    required: false
outputs:
  images:
    description: 'A comma-separated list of images that were published'
runs:
  using: 'node12'
  main: 'dist/main.js'
